const mongoose = require('mongoose');
const Plan = require('./models/Plan');
require('dotenv').config();

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/topify');
    console.log('MongoDB connected');
  } catch (error) {
    console.error('MongoDB connection error:', error);
    process.exit(1);
  }
};

const fixedPlans = [
  // JIO PLANS - Popular (8 plans)
  {
    operator: 'Jio',
    name: 'Popular Starter',
    price: 149,
    validity: '20',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioTV'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Recommended'
  },
  {
    operator: 'Jio',
    name: 'Best Seller',
    price: 199,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioTV'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Best Value'
  },
  {
    operator: 'Jio',
    name: 'Top Choice',
    price: 299,
    validity: '28',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioSaavn'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Popular'
  },
  {
    operator: 'Jio',
    name: 'Smart Plan',
    price: 179,
    validity: '24',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Smart Choice'
  },
  {
    operator: 'Jio',
    name: 'Value Pack',
    price: 239,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioTV'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Value Pack'
  },
  {
    operator: 'Jio',
    name: 'Premium Choice',
    price: 349,
    validity: '28',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioSaavn', 'JioTV'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Premium'
  },
  {
    operator: 'Jio',
    name: 'Family Plan',
    price: 399,
    validity: '28',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Jio Apps'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Family Pack'
  },
  {
    operator: 'Jio',
    name: 'Ultimate Popular',
    price: 449,
    validity: '28',
    data: '3.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema Premium', 'JioSaavn Pro'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Ultimate'
  },

  // JIO - Unlimited (7 plans)
  {
    operator: 'Jio',
    name: 'Truly Unlimited',
    price: 666,
    validity: '84',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Long Validity'
  },
  {
    operator: 'Jio',
    name: 'Unlimited Max',
    price: 719,
    validity: '84',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioSaavn'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Max Data'
  },
  {
    operator: 'Jio',
    name: 'Unlimited Pro',
    price: 999,
    validity: '84',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Jio Apps'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Pro Plan'
  },
  {
    operator: 'Jio',
    name: 'Unlimited Basic',
    price: 555,
    validity: '56',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Basic'
  },
  {
    operator: 'Jio',
    name: 'Unlimited Plus',
    price: 777,
    validity: '84',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioSaavn'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Plus Benefits'
  },
  {
    operator: 'Jio',
    name: 'Unlimited Premium',
    price: 1199,
    validity: '84',
    data: '4GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema Premium', 'JioSaavn Pro'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Premium'
  },
  {
    operator: 'Jio',
    name: 'Unlimited Super',
    price: 888,
    validity: '84',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioTV', 'JioSaavn'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Super Value'
  },

  // JIO - Data Packs (6 plans)
  {
    operator: 'Jio',
    name: 'Data Booster 1GB',
    price: 19,
    validity: '1',
    data: '1GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Quick Boost'
  },
  {
    operator: 'Jio',
    name: 'Data Booster 2GB',
    price: 29,
    validity: '1',
    data: '2GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Double Data'
  },
  {
    operator: 'Jio',
    name: 'Data Booster 5GB',
    price: 69,
    validity: '7',
    data: '5GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Weekly Pack'
  },
  {
    operator: 'Jio',
    name: 'Data Booster 10GB',
    price: 119,
    validity: '14',
    data: '10GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Fortnightly'
  },
  {
    operator: 'Jio',
    name: 'Data Booster 20GB',
    price: 199,
    validity: '28',
    data: '20GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Monthly Pack'
  },
  {
    operator: 'Jio',
    name: 'Data Booster 50GB',
    price: 399,
    validity: '56',
    data: '50GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Mega Pack'
  },

  // JIO - Annual (5 plans)
  {
    operator: 'Jio',
    name: 'Annual Basic',
    price: 2999,
    validity: '365',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Jio Apps'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Long Validity'
  },
  {
    operator: 'Jio',
    name: 'Annual Premium',
    price: 3999,
    validity: '365',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema Premium', 'JioSaavn Pro'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Premium Annual'
  },
  {
    operator: 'Jio',
    name: 'Annual Super',
    price: 4999,
    validity: '365',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Jio Apps Premium'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Super Annual'
  },
  {
    operator: 'Jio',
    name: 'Annual Value',
    price: 2499,
    validity: '365',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioCinema', 'JioTV'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Value Annual'
  },
  {
    operator: 'Jio',
    name: 'Annual Ultimate',
    price: 5999,
    validity: '365',
    data: '4GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Premium Apps'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Ultimate Annual'
  },

  // JIO - Talktime (5 plans)
  {
    operator: 'Jio',
    name: 'Talktime ₹22',
    price: 22,
    validity: '18',
    data: 'No',
    calls: '₹22 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Basic Talktime'
  },
  {
    operator: 'Jio',
    name: 'Talktime ₹49',
    price: 49,
    validity: '28',
    data: 'No',
    calls: '₹49 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Standard Talktime'
  },
  {
    operator: 'Jio',
    name: 'Talktime ₹99',
    price: 99,
    validity: '28',
    data: 'No',
    calls: '₹99 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Premium Talktime'
  },
  {
    operator: 'Jio',
    name: 'Talktime ₹149',
    price: 149,
    validity: '28',
    data: 'No',
    calls: '₹149 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'High Value'
  },
  {
    operator: 'Jio',
    name: 'Talktime ₹199',
    price: 199,
    validity: '28',
    data: 'No',
    calls: '₹199 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Max Talktime'
  },

  // AIRTEL PLANS - Popular (8 plans)
  {
    operator: 'Airtel',
    name: 'Smart Recharge',
    price: 155,
    validity: '24',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Recommended'
  },
  {
    operator: 'Airtel',
    name: 'Popular Choice',
    price: 179,
    validity: '28',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music', 'Airtel Thanks'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Best Value'
  },
  {
    operator: 'Airtel',
    name: 'Value Pack',
    price: 265,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music', 'Shaw Academy'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Value Pack'
  },
  {
    operator: 'Airtel',
    name: 'Smart Plus',
    price: 319,
    validity: '28',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music', 'Airtel Thanks'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Smart Plus'
  },
  {
    operator: 'Airtel',
    name: 'Premium Plan',
    price: 399,
    validity: '28',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music', 'Disney+ Hotstar'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Premium'
  },
  {
    operator: 'Airtel',
    name: 'Family Pack',
    price: 449,
    validity: '28',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Airtel Apps'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Family Pack'
  },
  {
    operator: 'Airtel',
    name: 'Ultimate Popular',
    price: 499,
    validity: '28',
    data: '3.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Disney+ Hotstar', 'Wynk Music Premium'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Ultimate'
  },
  {
    operator: 'Airtel',
    name: 'Super Value',
    price: 219,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Super Value'
  },

  // AIRTEL - Unlimited (6 plans)
  {
    operator: 'Airtel',
    name: 'Unlimited Basic',
    price: 549,
    validity: '56',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Basic Unlimited'
  },
  {
    operator: 'Airtel',
    name: 'Unlimited Plus',
    price: 699,
    validity: '84',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music', 'Airtel Thanks'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Plus Benefits'
  },
  {
    operator: 'Airtel',
    name: 'Unlimited Pro',
    price: 999,
    validity: '84',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Disney+ Hotstar', 'Wynk Music'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Pro Plan'
  },
  {
    operator: 'Airtel',
    name: 'Unlimited Max',
    price: 1199,
    validity: '84',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Premium Apps'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Max Data'
  },
  {
    operator: 'Airtel',
    name: 'Unlimited Super',
    price: 799,
    validity: '84',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music', 'Shaw Academy'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Super Value'
  },
  {
    operator: 'Airtel',
    name: 'Unlimited Premium',
    price: 1399,
    validity: '84',
    data: '4GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Disney+ Hotstar Premium', 'Wynk Music Premium'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Premium'
  },

  // AIRTEL - Data Packs (6 plans)
  {
    operator: 'Airtel',
    name: 'Data Add-on 1GB',
    price: 19,
    validity: '1',
    data: '1GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Quick Boost'
  },
  {
    operator: 'Airtel',
    name: 'Data Add-on 2GB',
    price: 29,
    validity: '1',
    data: '2GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Double Data'
  },
  {
    operator: 'Airtel',
    name: 'Data Add-on 5GB',
    price: 69,
    validity: '7',
    data: '5GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Weekly Pack'
  },
  {
    operator: 'Airtel',
    name: 'Data Add-on 10GB',
    price: 119,
    validity: '14',
    data: '10GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Fortnightly'
  },
  {
    operator: 'Airtel',
    name: 'Data Add-on 25GB',
    price: 249,
    validity: '28',
    data: '25GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Monthly Pack'
  },
  {
    operator: 'Airtel',
    name: 'Data Add-on 50GB',
    price: 449,
    validity: '56',
    data: '50GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Mega Pack'
  },

  // AIRTEL - Annual (5 plans)
  {
    operator: 'Airtel',
    name: 'Annual Basic',
    price: 2999,
    validity: '365',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Airtel Thanks'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Long Validity'
  },
  {
    operator: 'Airtel',
    name: 'Annual Premium',
    price: 3999,
    validity: '365',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Disney+ Hotstar', 'Wynk Music'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Premium Annual'
  },
  {
    operator: 'Airtel',
    name: 'Annual Super',
    price: 4999,
    validity: '365',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Premium Apps'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Super Annual'
  },
  {
    operator: 'Airtel',
    name: 'Annual Value',
    price: 2499,
    validity: '365',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Wynk Music'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Value Annual'
  },
  {
    operator: 'Airtel',
    name: 'Annual Ultimate',
    price: 5999,
    validity: '365',
    data: '4GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Disney+ Hotstar Premium', 'All Apps'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Ultimate Annual'
  },

  // AIRTEL - Talktime (5 plans)
  {
    operator: 'Airtel',
    name: 'Talktime ₹23',
    price: 23,
    validity: '18',
    data: 'No',
    calls: '₹23 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Basic Talktime'
  },
  {
    operator: 'Airtel',
    name: 'Talktime ₹49',
    price: 49,
    validity: '28',
    data: 'No',
    calls: '₹49 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Standard Talktime'
  },
  {
    operator: 'Airtel',
    name: 'Talktime ₹99',
    price: 99,
    validity: '28',
    data: 'No',
    calls: '₹99 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Premium Talktime'
  },
  {
    operator: 'Airtel',
    name: 'Talktime ₹149',
    price: 149,
    validity: '28',
    data: 'No',
    calls: '₹149 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'High Value'
  },
  {
    operator: 'Airtel',
    name: 'Talktime ₹199',
    price: 199,
    validity: '28',
    data: 'No',
    calls: '₹199 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Max Talktime'
  },

  // VI PLANS - Popular (8 plans)
  {
    operator: 'Vi',
    name: 'Value Starter',
    price: 157,
    validity: '28',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Recommended'
  },
  {
    operator: 'Vi',
    name: 'Smart Choice',
    price: 199,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV', 'Vi Music'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Best Value'
  },
  {
    operator: 'Vi',
    name: 'Premium Pack',
    price: 299,
    validity: '28',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV', 'Vi Music'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Premium'
  },
  {
    operator: 'Vi',
    name: 'Value Plus',
    price: 249,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Value Plus'
  },
  {
    operator: 'Vi',
    name: 'Family Plan',
    price: 399,
    validity: '28',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV Premium'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Family Pack'
  },
  {
    operator: 'Vi',
    name: 'Super Pack',
    price: 449,
    validity: '28',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Vi Apps'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Super Pack'
  },
  {
    operator: 'Vi',
    name: 'Ultimate Popular',
    price: 499,
    validity: '28',
    data: '3.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV Premium', 'Vi Music Premium'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Ultimate'
  },
  {
    operator: 'Vi',
    name: 'Smart Value',
    price: 229,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV'],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Smart Value'
  },

  // VI - Unlimited (6 plans)
  {
    operator: 'Vi',
    name: 'Unlimited Basic',
    price: 539,
    validity: '56',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Basic Unlimited'
  },
  {
    operator: 'Vi',
    name: 'Unlimited Plus',
    price: 719,
    validity: '84',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV', 'Vi Music'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Plus Benefits'
  },
  {
    operator: 'Vi',
    name: 'Unlimited Pro',
    price: 999,
    validity: '84',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV Premium'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Pro Plan'
  },
  {
    operator: 'Vi',
    name: 'Unlimited Max',
    price: 1199,
    validity: '84',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Vi Apps Premium'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Max Data'
  },
  {
    operator: 'Vi',
    name: 'Unlimited Super',
    price: 799,
    validity: '84',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV', 'Vi Music'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Super Value'
  },
  {
    operator: 'Vi',
    name: 'Unlimited Premium',
    price: 1399,
    validity: '84',
    data: '4GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Premium Vi Apps'],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Premium'
  },

  // VI - Data Packs (6 plans)
  {
    operator: 'Vi',
    name: 'Data Pack 1GB',
    price: 19,
    validity: '1',
    data: '1GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Quick Boost'
  },
  {
    operator: 'Vi',
    name: 'Data Pack 2GB',
    price: 29,
    validity: '1',
    data: '2GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Double Data'
  },
  {
    operator: 'Vi',
    name: 'Data Pack 5GB',
    price: 69,
    validity: '7',
    data: '5GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Weekly Pack'
  },
  {
    operator: 'Vi',
    name: 'Data Pack 10GB',
    price: 119,
    validity: '14',
    data: '10GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Fortnightly'
  },
  {
    operator: 'Vi',
    name: 'Data Pack 25GB',
    price: 249,
    validity: '28',
    data: '25GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Monthly Pack'
  },
  {
    operator: 'Vi',
    name: 'Data Pack 50GB',
    price: 449,
    validity: '56',
    data: '50GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Mega Pack'
  },

  // VI - Annual (5 plans)
  {
    operator: 'Vi',
    name: 'Annual Basic',
    price: 2999,
    validity: '365',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Long Validity'
  },
  {
    operator: 'Vi',
    name: 'Annual Premium',
    price: 3999,
    validity: '365',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV Premium', 'Vi Music'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Premium Annual'
  },
  {
    operator: 'Vi',
    name: 'Annual Super',
    price: 4999,
    validity: '365',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Vi Apps Premium'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Super Annual'
  },
  {
    operator: 'Vi',
    name: 'Annual Value',
    price: 2499,
    validity: '365',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Vi Movies & TV'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Value Annual'
  },
  {
    operator: 'Vi',
    name: 'Annual Ultimate',
    price: 5999,
    validity: '365',
    data: '4GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['All Premium Vi Apps'],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Ultimate Annual'
  },

  // VI - Talktime (5 plans)
  {
    operator: 'Vi',
    name: 'Talktime ₹22',
    price: 22,
    validity: '18',
    data: 'No',
    calls: '₹22 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Basic Talktime'
  },
  {
    operator: 'Vi',
    name: 'Talktime ₹49',
    price: 49,
    validity: '28',
    data: 'No',
    calls: '₹49 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Standard Talktime'
  },
  {
    operator: 'Vi',
    name: 'Talktime ₹99',
    price: 99,
    validity: '28',
    data: 'No',
    calls: '₹99 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Premium Talktime'
  },
  {
    operator: 'Vi',
    name: 'Talktime ₹149',
    price: 149,
    validity: '28',
    data: 'No',
    calls: '₹149 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'High Value'
  },
  {
    operator: 'Vi',
    name: 'Talktime ₹199',
    price: 199,
    validity: '28',
    data: 'No',
    calls: '₹199 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Max Talktime'
  },

  // BSNL PLANS - Popular (8 plans)
  {
    operator: 'BSNL',
    name: 'Budget Plan',
    price: 97,
    validity: '28',
    data: '2GB total',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Recommended'
  },
  {
    operator: 'BSNL',
    name: 'Value Pack',
    price: 147,
    validity: '28',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Best Value'
  },
  {
    operator: 'BSNL',
    name: 'Smart Plan',
    price: 197,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Smart Choice'
  },
  {
    operator: 'BSNL',
    name: 'Premium Choice',
    price: 247,
    validity: '28',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Premium'
  },
  {
    operator: 'BSNL',
    name: 'Family Plan',
    price: 297,
    validity: '28',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Family Pack'
  },
  {
    operator: 'BSNL',
    name: 'Super Pack',
    price: 347,
    validity: '28',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Super Pack'
  },
  {
    operator: 'BSNL',
    name: 'Economy Plan',
    price: 127,
    validity: '28',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Economy'
  },
  {
    operator: 'BSNL',
    name: 'Standard Pack',
    price: 177,
    validity: '28',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: true,
    category: 'Popular',
    type: 'prepaid',
    highlight: 'Standard'
  },

  // BSNL - Unlimited (6 plans)
  {
    operator: 'BSNL',
    name: 'Unlimited Basic',
    price: 187,
    validity: '28',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Basic Unlimited'
  },
  {
    operator: 'BSNL',
    name: 'Unlimited Plus',
    price: 397,
    validity: '56',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Plus Benefits'
  },
  {
    operator: 'BSNL',
    name: 'Unlimited Pro',
    price: 597,
    validity: '84',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Pro Plan'
  },
  {
    operator: 'BSNL',
    name: 'Unlimited Max',
    price: 797,
    validity: '84',
    data: '3GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Max Data'
  },
  {
    operator: 'BSNL',
    name: 'Unlimited Super',
    price: 997,
    validity: '84',
    data: '4GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Super Value'
  },
  {
    operator: 'BSNL',
    name: 'Unlimited Value',
    price: 297,
    validity: '56',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Unlimited',
    type: 'prepaid',
    highlight: 'Value Pack'
  },

  // BSNL - Data Packs (6 plans)
  {
    operator: 'BSNL',
    name: 'Data Pack 1GB',
    price: 16,
    validity: '1',
    data: '1GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Quick Boost'
  },
  {
    operator: 'BSNL',
    name: 'Data Pack 2GB',
    price: 26,
    validity: '1',
    data: '2GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Double Data'
  },
  {
    operator: 'BSNL',
    name: 'Data Pack 5GB',
    price: 56,
    validity: '7',
    data: '5GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Weekly Pack'
  },
  {
    operator: 'BSNL',
    name: 'Data Pack 10GB',
    price: 96,
    validity: '14',
    data: '10GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Fortnightly'
  },
  {
    operator: 'BSNL',
    name: 'Data Pack 25GB',
    price: 196,
    validity: '28',
    data: '25GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Monthly Pack'
  },
  {
    operator: 'BSNL',
    name: 'Data Pack 50GB',
    price: 396,
    validity: '56',
    data: '50GB',
    calls: 'No',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Data Packs',
    type: 'prepaid',
    highlight: 'Mega Pack'
  },

  // BSNL - Annual (5 plans)
  {
    operator: 'BSNL',
    name: 'Annual Basic',
    price: 1999,
    validity: '365',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Long Validity'
  },
  {
    operator: 'BSNL',
    name: 'Annual Premium',
    price: 2499,
    validity: '365',
    data: '1.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Premium Annual'
  },
  {
    operator: 'BSNL',
    name: 'Annual Super',
    price: 2999,
    validity: '365',
    data: '2GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Super Annual'
  },
  {
    operator: 'BSNL',
    name: 'Annual Value',
    price: 1799,
    validity: '365',
    data: '1GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Value Annual'
  },
  {
    operator: 'BSNL',
    name: 'Annual Ultimate',
    price: 3499,
    validity: '365',
    data: '2.5GB/day',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: [],
    popular: false,
    category: 'Annual',
    type: 'prepaid',
    highlight: 'Ultimate Annual'
  },

  // BSNL - Talktime (5 plans)
  {
    operator: 'BSNL',
    name: 'Talktime ₹22',
    price: 22,
    validity: '18',
    data: 'No',
    calls: '₹22 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Basic Talktime'
  },
  {
    operator: 'BSNL',
    name: 'Talktime ₹47',
    price: 47,
    validity: '28',
    data: 'No',
    calls: '₹47 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Standard Talktime'
  },
  {
    operator: 'BSNL',
    name: 'Talktime ₹97',
    price: 97,
    validity: '28',
    data: 'No',
    calls: '₹97 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Premium Talktime'
  },
  {
    operator: 'BSNL',
    name: 'Talktime ₹147',
    price: 147,
    validity: '28',
    data: 'No',
    calls: '₹147 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'High Value'
  },
  {
    operator: 'BSNL',
    name: 'Talktime ₹197',
    price: 197,
    validity: '28',
    data: 'No',
    calls: '₹197 Talktime',
    sms: 'No',
    benefits: [],
    popular: false,
    category: 'Talktime',
    type: 'prepaid',
    highlight: 'Max Talktime'
  }
];

const seedFixedPlans = async () => {
  try {
    await connectDB();
    
    // Clear existing plans
    await Plan.deleteMany({});
    console.log('Cleared existing plans');
    
    // Insert fixed plans
    await Plan.insertMany(fixedPlans);
    console.log('Fixed plans inserted successfully');
    
    console.log(`✅ Seeded ${fixedPlans.length} plans`);
    console.log('Plans per operator:');
    console.log('- Jio: 31 plans (8 Popular, 7 Unlimited, 6 Data, 5 Annual, 5 Talktime)');
    console.log('- Airtel: 32 plans (8 Popular, 6 Unlimited, 6 Data, 5 Annual, 5 Talktime)');
    console.log('- Vi: 32 plans (8 Popular, 6 Unlimited, 6 Data, 5 Annual, 5 Talktime)');
    console.log('- BSNL: 32 plans (8 Popular, 6 Unlimited, 6 Data, 5 Annual, 5 Talktime)');
    console.log(`Total: ${fixedPlans.length} plans`);
    
    process.exit(0);
  } catch (error) {
    console.error('Error seeding fixed plans:', error);
    process.exit(1);
  }
};

seedFixedPlans();